
services:
  postgres:

    image: postgres:18 
    container_name: transpobolivia-db
    restart: always
    
    environment:
      POSTGRES_DB: transpobolivia_db  
      POSTGRES_USER: user             
      POSTGRES_PASSWORD: password     
   
    ports:
      - "5433:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql